### PR TITLE
Readme tweaks

### PR DESCRIPTION
**Pull request by apohllo**
Fix `__file__` -> `__name__` error and add Python syntax highlighting.

### CODE REVIEW

**Comment by apohllo** [comment]
The error occurs only when you run the code in Python console. Still, I think people will run the code in console on many occasions, so it's better to make it compatible with this scenario.

**Comment by apohllo** [comment]
But it might not make sense, tu use `__name__` since the code will generate an empty string. So maybe we should just default to "." instead, without a reference to either `__name__` or `__file__`?

**Comment by IgorTest19** [comment]
A solution that resolves this error may be the usage of absolute path, in this case: 
`base_dir = os.path.join(os.path.abspath(''))`. It was checked in environments like `Windows` and `Google Colab` (no errors were returned) but it needs further testing. Also, the functionalities included in the `README.md` file could be implemented within the package, just to be invoked by single functions.

Another approach, more proper one is to create a function which checks environments and based on that, applies proper path of the directory.

**Comment by IgorTest19** [comment]
Fix was included in the Pull Request: [#25](https://github.com/speakleash/speakleash/pull/25)

**Pull request closed without merging**
